In [1]:
from qpms import *

In [2]:
R = 40e-9
ω_p = 9*eV/ℏ #9*eV/ℏ
ε_inf = 4.6
γ_p = 0.1*eV/ℏ
ε_b = 2.13
lMax = 3

ω = 1.5*eV/ℏ

In [3]:
ε_m = ε_drude(ε_inf, ω_p, γ_p, ω)

In [4]:
k_i = cmath.sqrt(ε_m)*ω/c
k_e = cmath.sqrt(ε_b)*ω/c
RH, RV, TH, TV = mie_coefficients(a=R, nmax=lMax, k_i=k_i, k_e=k_e, J_ext=1, J_scat=3)

In [5]:
spec = BaseSpec(lMax=lMax)
cT = CTMatrix.spherical(spec, R, k_i, k_e)
cT2 = CTMatrix.spherical_perm(spec, R, ω, ε_m, ε_b)

In [6]:
print(np.diag(cT[...]))
print(np.diag(cT2[...]))

[-8.65695571e-03+8.28056150e-02j -8.65695571e-03+8.28056150e-02j
 -8.65695571e-03+8.28056150e-02j -1.01374924e-05+6.86429828e-04j
 -1.01374924e-05+6.86429828e-04j -1.01374924e-05+6.86429828e-04j
 -1.01374924e-05+6.86429828e-04j -1.01374924e-05+6.86429828e-04j
 -4.22848639e-08+3.33994147e-06j -4.22848639e-08+3.33994147e-06j
 -4.22848639e-08+3.33994147e-06j -4.22848639e-08+3.33994147e-06j
 -4.22848639e-08+3.33994147e-06j -4.22848639e-08+3.33994147e-06j
 -4.22848639e-08+3.33994147e-06j -2.64247535e-04-4.45370427e-03j
 -2.64247535e-04-4.45370427e-03j -2.64247535e-04-4.45370427e-03j
 -1.82540869e-06-2.89871164e-05j -1.82540869e-06-2.89871164e-05j
 -1.82540869e-06-2.89871164e-05j -1.82540869e-06-2.89871164e-05j
 -1.82540869e-06-2.89871164e-05j -6.35422018e-09-9.58472627e-08j
 -6.35422018e-09-9.58472627e-08j -6.35422018e-09-9.58472627e-08j
 -6.35422018e-09-9.58472627e-08j -6.35422018e-09-9.58472627e-08j
 -6.35422018e-09-9.58472627e-08j -6.35422018e-09-9.58472627e-08j]
[-8.65695571e-03+8.28056

In [7]:
print(RV)
print(RH)

[9.59341021e-01-1.64912412e-01j 8.65695571e-03-8.28056150e-02j
 1.01374924e-05-6.86429828e-04j 4.22848639e-08-3.33994147e-06j]
[4.74300963e-02+1.96142656e-01j 2.64247535e-04+4.45370427e-03j
 1.82540869e-06+2.89871164e-05j 6.35422018e-09+9.58472627e-08j]


In [8]:
print (k_i, k_e)

(1623614.1219376698+42518906.788178295j) (11094164.321117919+0j)


In [9]:
zJn(4, R*k_i, J=1)

(array([ 1.55539427-0.04860786j,  0.04390095+0.74778921j,
        -0.2353209 +0.02157796j, -0.00693583-0.05456515j,
         0.0099793 -0.00163621j]),
 array([-0.04390095-0.74778921j,  0.67534536-0.03058793j,
         0.02172188+0.33185477j, -0.10655427+0.01018267j,
        -0.00325125-0.02508662j]))

In [10]:
R*k_i

(0.0649445648775068+1.7007562715271318j)

In [11]:
R*k_e

(0.44376657284471677+0j)

In [12]:
au = MaterialInterpolator("/u/46/necadam1/unix/repo/refractiveindex.info-database/database/data/main/Au/Johnson.yml")

In [13]:
a, b = au.freq_interval

In [14]:
au(a), au(b)

((-189.042+25.3552j), (0.2270560000000008+3.0412800000000004j))

In [15]:
gensphere = TMatrixGenerator.sphere(outside=EpsMu(2.3104,1), inside=lorentz_drude['Au'], r=50e-9)

In [16]:
np.diag(gensphere(spec,ω)[...])

array([-4.36161252e-02+2.28777313e-01j, -4.36161252e-02+2.28777313e-01j,
       -4.36161252e-02+2.28777313e-01j,  6.69388553e-05+2.82301754e-03j,
        6.69388553e-05+2.82301754e-03j,  6.69388553e-05+2.82301754e-03j,
        6.69388553e-05+2.82301754e-03j,  6.69388553e-05+2.82301754e-03j,
        5.26383985e-07+2.27442471e-05j,  5.26383985e-07+2.27442471e-05j,
        5.26383985e-07+2.27442471e-05j,  5.26383985e-07+2.27442471e-05j,
        5.26383985e-07+2.27442471e-05j,  5.26383985e-07+2.27442471e-05j,
        5.26383985e-07+2.27442471e-05j,  5.50796078e-04-1.09082834e-02j,
        5.50796078e-04-1.09082834e-02j,  5.50796078e-04-1.09082834e-02j,
        8.98597111e-06-1.24160370e-04j,  8.98597111e-06-1.24160370e-04j,
        8.98597111e-06-1.24160370e-04j,  8.98597111e-06-1.24160370e-04j,
        8.98597111e-06-1.24160370e-04j,  5.43611838e-08-7.04806605e-07j,
        5.43611838e-08-7.04806605e-07j,  5.43611838e-08-7.04806605e-07j,
        5.43611838e-08-7.04806605e-07j,  5.43611838

In [17]:
gensphere_arc_e = TMatrixGenerator.sphere_asarc(outside=EpsMu(2.3104,1), inside=lorentz_drude['Au'], r=50e-9, lMax_extend=4)

In [18]:
np.diag(gensphere_arc_e(spec,ω)[...])

array([-4.53291311e-02+2.77611240e-01j, -4.24745641e-02+2.24803564e-01j,
       -4.53291311e-02+2.77611240e-01j,  7.59828052e-05+2.86173977e-03j,
        2.67924426e-04+3.27996083e-03j,  6.12439335e-05+2.78122400e-03j,
        2.67924426e-04+3.27996083e-03j,  7.59828052e-05+2.86173977e-03j,
        5.69091719e-07+2.29533748e-05j,  7.44989773e-07+2.37478758e-05j,
        4.22749693e-06+3.17730935e-05j,  5.40025153e-07+2.28077382e-05j,
        4.22749693e-06+3.17730935e-05j,  7.44989773e-07+2.37478758e-05j,
        5.69091719e-07+2.29533748e-05j, -7.80983857e-03-3.44655930e-02j,
        5.91005854e-04-1.02266640e-02j, -7.80983857e-03-3.44655930e-02j,
       -3.41168862e-06-2.11325513e-04j, -4.26228556e-04-1.57386273e-03j,
        9.53065100e-06-9.70458160e-05j, -4.26228556e-04-1.57386273e-03j,
       -3.41168862e-06-2.11325513e-04j, -8.06713531e-09-1.25923000e-06j,
       -2.96115400e-07-3.42442056e-06j, -6.04052841e-06-2.10234142e-05j,
        5.17684380e-08-8.84008077e-07j, -6.04052841

In [19]:
%timeit gensphere_arc_e(spec,ω)

242 ms ± 10.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
gensphere_arc = TMatrixGenerator.sphere_asarc(outside=EpsMu(2.3104,1), inside=lorentz_drude['Au'], r=50e-9)

In [21]:
np.diag(gensphere_arc(spec,ω)[...])

array([-4.60991076e-02+2.45375236e-01j, -4.24745641e-02+2.24803564e-01j,
       -4.60991076e-02+2.45375236e-01j,  7.83627915e-05+2.88004874e-03j,
        2.26800427e-04+3.38020339e-03j,  6.69388553e-05+2.82301754e-03j,
        2.26800427e-04+3.38020339e-03j,  7.83627915e-05+2.88004874e-03j,
        5.26383985e-07+2.27442471e-05j,  5.97186683e-07+2.30944357e-05j,
        1.17333548e-06+2.52925612e-05j,  5.40025153e-07+2.28077382e-05j,
        1.17333548e-06+2.52925612e-05j,  5.97186683e-07+2.30944357e-05j,
        5.26383985e-07+2.27442471e-05j, -2.62762760e-03-2.35409249e-02j,
        5.91005854e-04-1.02266640e-02j, -2.62762760e-03-2.35409249e-02j,
       -3.10310863e-06-2.25424818e-04j, -1.51702901e-04-1.20516540e-03j,
        8.98597111e-06-1.24160370e-04j, -1.51702901e-04-1.20516540e-03j,
       -3.10310863e-06-2.25424818e-04j,  5.43611838e-08-7.04806605e-07j,
       -6.67964145e-08-1.70585106e-06j, -1.27417465e-06-7.98107417e-06j,
        5.17684380e-08-8.84008077e-07j, -1.27417465

In [22]:
spec1 = BaseSpec(lMax=1)
np.diag(gensphere_arc(spec1,ω)[...])

array([-0.04361613+0.22877731j, -0.04361613+0.22877731j,
       -0.04361613+0.22877731j,  0.0005508 -0.01090828j,
        0.0005508 -0.01090828j,  0.0005508 -0.01090828j])

In [23]:
spec.norm

<VSWFNorm.POWERNORM_CS: 65544>

In [24]:
spec1.norm

<VSWFNorm.POWERNORM_CS: 65544>