In [44]:
from qpms import ScatteringSystem, Particle, EpsMu, EpsMuGenerator, lorentz_drude, eV, hbar, TMatrixGenerator, BaseSpec
eh = eV/hbar
import numpy as np
np.set_printoptions(linewidth=200, precision=5, suppress=True)z

In [48]:
px = 590e-9
py = 580e-9
lattice_basis1 = ((px, 0., 0.), (0., py, 0.))
lattice_basis2 = ((2*px, 0., 0.), (0., py, 0.))
bg = EpsMuGenerator(EpsMu(1.9))
fg = EpsMuGenerator(lorentz_drude['Au'])
tmg = TMatrixGenerator.sphere(bg, fg, 30e-9)
bspec = BaseSpec(lMax=1)

pos1 = (0.,0.,0.)
pos2 = (px, 0., 0.)

omega = (1.4-0.01j)*eh
p1 = Particle(pos1, tmg, bspec)
p2 = Particle(pos2, tmg, bspec)

ss1, ssw1 = ScatteringSystem.create([p1,], bg, omega, latticebasis = lattice_basis1)
ss2, ssw2 = ScatteringSystem.create([p1, p2], bg, omega, latticebasis = lattice_basis2)

In [49]:
kvec = (1e6,2e5,0)
w1 = ssw1.translation_matrix_full(kvec)
w2 = ssw2.translation_matrix_full(kvec)

In [50]:
w1

array([[0.09216+0.10021j, 0.     +0.j     , 0.80388+0.59943j, 0.     +0.j     , 0.     +0.j     , 0.     +0.j     ],
       [0.     +0.j     , 0.51852+0.20724j, 0.     +0.j     , 0.     +0.j     , 0.     +0.j     , 0.     +0.j     ],
       [0.78422+0.66146j, 0.     +0.j     , 0.09216+0.10021j, 0.     +0.j     , 0.     +0.j     , 0.     +0.j     ],
       [0.     +0.j     , 0.     +0.j     , 0.     +0.j     , 0.09216+0.10021j, 0.     +0.j     , 0.80388+0.59943j],
       [0.     +0.j     , 0.     +0.j     , 0.     +0.j     , 0.     +0.j     , 0.51852+0.20724j, 0.     +0.j     ],
       [0.     +0.j     , 0.     +0.j     , 0.     +0.j     , 0.78422+0.66146j, 0.     +0.j     , 0.09216+0.10021j]])

In [51]:
w2

array([[-0.16855+0.10885j,  0.     +0.j     ,  0.46012+0.46129j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.26071-0.00864j,  0.     +0.j     ,  0.34376+0.13814j,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     , -0.14624+0.10874j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.66477+0.09849j,  0.     +0.j     ,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.44589+0.49067j,  0.     +0.j     , -0.16855+0.10885j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.33833+0.17079j,  0.     +0.j     ,  0.26071-0.00864j,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     , -0.16855+0.10885j,  0.     +0.j     ,  0.46012+0.46129j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.26071-0.00864j,
         0.     +0.j     ,  0.34376+0.13814j],
       [ 0.     +0.j

In [52]:
w2[0:6,0:6]+w2[6:12,0:6]-w1

array([[-0.-0.j,  0.+0.j,  0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.-0.j,  0.+0.j, -0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -0.-0.j,  0.+0.j,  0.-0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -0.-0.j,  0.+0.j, -0.-0.j]])

In [53]:
w2[0:6,0:6]-w2[6:12,6:12]

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [54]:
w2[0:6,6:12]-w2[6:12,0:6]

array([[ 0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j]])

In [55]:
m1 = ssw1.modeproblem_matrix_full(kvec)
m2 = ssw2.modeproblem_matrix_full(kvec)

In [56]:
m1

array([[ 1.00227-0.00202j,  0.     +0.j     ,  0.01367-0.01771j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     ,  1.00482-0.01149j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ],
       [ 0.01505-0.01725j,  0.     +0.j     ,  1.00227-0.00202j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.99994+0.00007j,  0.     +0.j     , -0.00034+0.00056j],
       [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.9999 +0.00035j,  0.     +0.j     ],
       [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     , -0.00038+0.00055j,  0.     +0.j     ,  0.99994+0.00007j]])

In [57]:
m2

array([[ 1.00236+0.0038j ,  0.     +0.j     ,  0.01046-0.01009j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     , -0.00009-0.00582j,  0.     +0.j     ,  0.00321-0.00762j,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     ,  1.00237+0.0033j ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.00245-0.01479j,  0.     +0.j     ,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.01111-0.00976j,  0.     +0.j     ,  1.00236+0.0038j ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.00394-0.00748j,  0.     +0.j     , -0.00009-0.00582j,  0.     +0.j     ,
         0.     +0.j     ,  0.     +0.j     ],
       [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.99992-0.0001j ,  0.     +0.j     , -0.00027+0.00033j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.00002+0.00017j,
         0.     +0.j     , -0.00007+0.00023j],
       [ 0.     +0.j

In [58]:
m2[0:6,0:6]+m2[6:12,0:6]-m1

array([[-0.+0.j,  0.+0.j, -0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j,  0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j,  0.-0.j]])

In [59]:
np.linalg.svd(m1)

(array([[-0.70683+0.01356j, -0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.70716+0.01107j],
        [ 0.     +0.j     ,  0.02756+0.99962j,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ],
        [-0.70725+0.00216j, -0.     -0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     , -0.70661-0.02247j],
        [ 0.     +0.j     ,  0.     +0.j     , -0.7071 +0.00035j,  0.     -0.j     ,  0.70711+0.00044j,  0.     +0.j     ],
        [ 0.     +0.j     ,  0.     +0.j     ,  0.     +0.j     ,  0.01216+0.99993j,  0.     +0.j     ,  0.     +0.j     ],
        [ 0.     +0.j     ,  0.     +0.j     ,  0.70706+0.0085j , -0.     -0.j     ,  0.70704+0.00929j,  0.     +0.j     ]]),
 array([1.01682, 1.00488, 1.0003 , 0.9999 , 0.99958, 0.98803]),
 array([[-0.70725+0.j     ,  0.     +0.j     , -0.70687+0.0114j , -0.     +0.j     , -0.     +0.j     ,  0.     +0.j     ],
        [-0.     +0.j     ,  0.01613-0.99987j,  0.     +0.j     , 

In [60]:
np.linalg.svd(m2)

(array([[-0.49981+0.00959j,  0.5    +0.00359j, -0.     +0.j     ,  0.     -0.j     ,  0.     +0.j     , -0.     -0.j     , -0.     -0.j     ,  0.     +0.j     , -0.     +0.j     , -0.     +0.j     ,
         -0.49995-0.00603j,  0.50004+0.00783j],
        [-0.     +0.j     , -0.     +0.j     ,  0.70406+0.06559j, -0.     +0.j     ,  0.     +0.j     , -0.70014+0.09904j, -0.     +0.j     ,  0.     -0.j     ,  0.     +0.j     ,  0.     +0.j     ,
         -0.     -0.j     , -0.     -0.j     ],
        [-0.5001 +0.00152j,  0.49987+0.01039j,  0.     +0.j     , -0.     -0.j     ,  0.     -0.j     , -0.     +0.j     , -0.     +0.j     ,  0.     -0.j     , -0.     +0.j     ,  0.     +0.j     ,
          0.49985+0.01283j, -0.49965-0.01589j],
        [ 0.     +0.j     ,  0.     +0.j     , -0.     -0.j     ,  0.01195+0.49985j, -0.01188-0.49986j, -0.     -0.j     ,  0.     +0.j     , -0.     -0.j     , -0.01179-0.49986j, -0.01139-0.49987j,
          0.     +0.j     ,  0.     +0.j     ],
        [ 0.