In [1]:
import numpy as np
import qpms
import spherical_functions as sf, quaternion
qpms.__version__

'0.2.14'

In [2]:
lMax=2
tc = qpms.trans_calculator(lMax)
my, ny = qpms.get_mn_y(lMax)
nelem = len(my)

In [3]:
qpms.yflip_tyty(lMax).reshape((2*nelem,2*nelem))

array([[ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [ ]:
d1_cart = np.array([0.1,0,0])#np.random.normal(scale=10, size=(3,)) # translation vector in basis 1
rot21_cart = np.array([0,0,0.01])#np.random.normal(size=(3,)) # random rotation vector
rot21_quat = quaternion.from_rotation_vector(rot21_cart)
rot21_matrix = quaternion.as_rotation_matrix(rot21_quat) # rotation matrix from basis 1 to basis 2
d2_cart = np.dot(rot21_matrix, d1_cart) # translation vector in basis 2
D21_yy = qpms.WignerD_yy_fromvector(lMax,rot21_cart)
D12_yy = qpms.WignerD_yy_fromvector(lMax,-rot21_cart)

d1_sph = qpms.cart2sph(d1_cart)
r1, th1, fi1 = d1_sph
d2_sph = qpms.cart2sph(d2_cart)
r2, th2, fi2 = d2_sph

S1 = tc.get_AB_arrays(np.array(r1), np.array(th1), np.array(fi1), np.array(False), 1)
S2 = tc.get_AB_arrays(np.array(r2), np.array(th2), np.array(fi2), np.array(False), 1)




In [1]:
np.set_printoptions(precision=5, linewidth=200)

NameError: name 'np' is not defined

In [ ]:
( #test for unitarity of the Wigner matrix
    np.all(np.isclose(D12_yy.conj().T,D21_yy)) and  
    np.all(np.isclose(np.dot(D12_yy,D21_yy), np.eye(nelem))) 
)

In [7]:
# The "vector" part
#S2nA = np.dot(np.dot(D21_yy, S1[0]), D12_yy) # FIXME!!!
S2nA = np.dot(np.dot(D21_yy, S1[0]), D12_yy) # FIXME!!!

In [8]:
th2

1.5707963267948966

In [9]:
np.angle(S2nA)

array([[-1.56948, -1.5808 ,  1.5508 , -1.5608 , -1.5708 ,  1.5608 ,  1.5508 , -1.6008 ],
       [-1.55948, -1.5708 ,  1.5608 , -1.5508 , -1.5608 ,  1.5708 ,  1.5608 , -1.5908 ],
       [-1.54948, -1.5608 ,  1.5708 , -1.5408 , -1.5508 ,  1.5808 ,  1.5708 , -1.5808 ],
       [-1.57948, -1.5908 ,  1.5408 , -1.5708 , -1.5808 ,  1.5508 ,  1.5408 , -1.6108 ],
       [-1.56948, -1.5808 ,  1.5508 , -1.5608 , -1.5708 ,  1.5608 ,  1.5508 , -1.6008 ],
       [-1.55948, -1.5708 ,  1.5608 , -1.5508 , -1.5608 ,  1.5708 ,  1.5608 , -1.5908 ],
       [-1.54948, -1.5608 ,  1.5708 , -1.5408 , -1.5508 ,  1.5808 ,  1.5708 , -1.5808 ],
       [-1.53948, -1.5508 ,  1.5808 , -1.5308 , -1.5408 ,  1.5908 ,  1.5808 , -1.5708 ]])

In [10]:
np.angle(S2[0])

array([[-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ],
       [-1.56948, -1.5608 ,  1.5908 , -1.5808 , -1.5708 ,  1.5808 ,  1.5908 , -1.5408 ]])

In [11]:
np.angle(S1[0])

array([[-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ],
       [-1.56948, -1.5708 ,  1.5708 , -1.5708 , -1.5708 ,  1.5708 ,  1.5708 , -1.5708 ]])

In [12]:
np.angle(D12_yy)

array([[ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.02,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.01,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.02]])

In [13]:
np.abs(S1)

array([[[  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23443e+05,   3.08378e-11,   2.51809e+05],
        [  7.61204e+02,   1.95166e-13,   2.25376e+03,   5.05641e+04,   1.85150e-11,   1.23

In [27]:
rot21_cart

array([ 0.  ,  0.  ,  0.01])

In [14]:
S1

(array([[  9.98501e-01 -7.61203e+02j,   4.32669e-20 -1.95166e-13j,  -4.99643e-04 +2.25376e+03j,   6.70182e-02 -5.05641e+04j,   4.10466e-18 -1.85150e-11j,  -2.73666e-02 +1.23443e+05j,
          -1.95491e-21 +3.08378e-11j,   1.59630e-05 -2.51809e+05j],
        [  9.98501e-01 -7.61203e+02j,   4.32669e-20 -1.95166e-13j,  -4.99643e-04 +2.25376e+03j,   6.70182e-02 -5.05641e+04j,   4.10466e-18 -1.85150e-11j,  -2.73666e-02 +1.23443e+05j,
          -1.95491e-21 +3.08378e-11j,   1.59630e-05 -2.51809e+05j],
        [  9.98501e-01 -7.61203e+02j,   4.32669e-20 -1.95166e-13j,  -4.99643e-04 +2.25376e+03j,   6.70182e-02 -5.05641e+04j,   4.10466e-18 -1.85150e-11j,  -2.73666e-02 +1.23443e+05j,
          -1.95491e-21 +3.08378e-11j,   1.59630e-05 -2.51809e+05j],
        [  9.98501e-01 -7.61203e+02j,   4.32669e-20 -1.95166e-13j,  -4.99643e-04 +2.25376e+03j,   6.70182e-02 -5.05641e+04j,   4.10466e-18 -1.85150e-11j,  -2.73666e-02 +1.23443e+05j,
          -1.95491e-21 +3.08378e-11j,   1.59630e-05 -2.51809e+05

In [15]:
S2

(array([[  9.98501e-01 -7.61203e+02j,   1.95167e-15 -1.95156e-13j,  -4.50727e+01 +2.25331e+03j,  -5.05566e+02 -5.05616e+04j,   4.10466e-18 -1.85150e-11j,  -1.23444e+03 +1.23437e+05j,
          -6.16714e-13 +3.08316e-11j,   7.55315e+03 -2.51696e+05j],
        [  9.98501e-01 -7.61203e+02j,   1.95167e-15 -1.95156e-13j,  -4.50727e+01 +2.25331e+03j,  -5.05566e+02 -5.05616e+04j,   4.10466e-18 -1.85150e-11j,  -1.23444e+03 +1.23437e+05j,
          -6.16714e-13 +3.08316e-11j,   7.55315e+03 -2.51696e+05j],
        [  9.98501e-01 -7.61203e+02j,   1.95167e-15 -1.95156e-13j,  -4.50727e+01 +2.25331e+03j,  -5.05566e+02 -5.05616e+04j,   4.10466e-18 -1.85150e-11j,  -1.23444e+03 +1.23437e+05j,
          -6.16714e-13 +3.08316e-11j,   7.55315e+03 -2.51696e+05j],
        [  9.98501e-01 -7.61203e+02j,   1.95167e-15 -1.95156e-13j,  -4.50727e+01 +2.25331e+03j,  -5.05566e+02 -5.05616e+04j,   4.10466e-18 -1.85150e-11j,  -1.23444e+03 +1.23437e+05j,
          -6.16714e-13 +3.08316e-11j,   7.55315e+03 -2.51696e+05