In [1]:
import numpy as np
import qpms
import spherical_functions as sf, quaternion
qpms.__version__

'0.2.14'

In [2]:
lMax=2
tc = qpms.trans_calculator(lMax)
my, ny = qpms.get_mn_y(lMax)
nelem = len(my)

In [3]:
qpms.yflip_tyty(lMax).reshape((2*nelem,2*nelem))

array([[ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [4]:
d1_cart = np.array([0.1,0,0])#np.random.normal(scale=10, size=(3,)) # translation vector in basis 1
rot21_cart = np.array([0,0,0.01])#np.random.normal(size=(3,)) # random rotation vector
rot21_quat = quaternion.from_rotation_vector(rot21_cart)
rot21_matrix = quaternion.as_rotation_matrix(rot21_quat) # rotation matrix from basis 1 to basis 2
d2_cart = np.dot(rot21_matrix, d1_cart) # translation vector in basis 2
D21_yy = qpms.WignerD_yy_fromvector(lMax,rot21_cart)
D12_yy = qpms.WignerD_yy_fromvector(lMax,-rot21_cart)

d1_sph = qpms.cart2sph(d1_cart)
r1, th1, fi1 = d1_sph
d2_sph = qpms.cart2sph(d2_cart)
r2, th2, fi2 = d2_sph

S1 = tc.get_AB_arrays(np.array(r1), np.array(th1), np.array(fi1), np.array(True), 3)
S2 = tc.get_AB_arrays(np.array(r2), np.array(th2), np.array(fi2), np.array(True), 3)




In [5]:
np.set_printoptions(precision=5, linewidth=200)

In [6]:
( #test for unitarity of the Wigner matrix
    np.all(np.isclose(D12_yy.conj().T,D21_yy)) and  
    np.all(np.isclose(np.dot(D12_yy,D21_yy), np.eye(nelem))) 
)

True

In [7]:
# The "vector" part
#S2nA = np.dot(np.dot(D21_yy, S1[0]), D12_yy) # FIXME!!!
S2nA = np.dot(np.dot(D21_yy, S1[0]), D12_yy) # FIXME!!!

In [8]:
th2

1.5707963267948966

In [9]:
np.angle(S2nA)

array([[ 0.     , -0.01   ,  3.12159,  0.01   ,  0.     ,  3.13159,  3.12159, -0.03   ],
       [ 0.01   ,  0.     ,  3.13159,  0.02   ,  0.01   ,  3.14159,  3.13159, -0.02   ],
       [ 0.02   ,  0.01   ,  3.14159,  0.03   ,  0.02   , -3.13159,  3.14159, -0.01   ],
       [-0.01   , -0.02   ,  3.11159,  0.     , -0.01   ,  3.12159,  3.11159, -0.04   ],
       [ 0.     , -0.01   ,  3.12159,  0.01   ,  0.     ,  3.13159,  3.12159, -0.03   ],
       [ 0.01   ,  0.     ,  3.13159,  0.02   ,  0.01   ,  3.14159,  3.13159, -0.02   ],
       [ 0.02   ,  0.01   ,  3.14159,  0.03   ,  0.02   , -3.13159,  3.14159, -0.01   ],
       [ 0.03   ,  0.02   , -3.13159,  0.04   ,  0.03   , -3.12159, -3.13159,  0.     ]])

In [10]:
np.angle(S2[0])

array([[ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ],
       [ 0.     ,  0.01   , -3.12159, -0.01   ,  0.     , -3.13159, -3.12159,  0.03   ]])

In [11]:
np.angle(S1[0])

array([[ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ],
       [ 0.     ,  0.     ,  3.14159,  0.     ,  0.     ,  3.14159,  3.14159,  0.     ]])

In [12]:
np.angle(D12_yy)

array([[ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.02,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.01,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.02]])

In [13]:
np.abs(S1)

array([[[  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73666e-02,   1.95491e-21,   1.59630e-05],
        [  9.98501e-01,   4.32669e-20,   4.99643e-04,   6.70182e-02,   4.10466e-18,   2.73

In [14]:
S1

(array([[  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j,   4.32669e-20+0.j,  -4.99643e-04+0.j,   6.70182e-02+0.j,   4.10466e-18+0.j,  -2.73666e-02+0.j,  -1.95491e-21+0.j,   1.59630e-05+0.j],
        [  9.98501e-01+0.j, 

In [15]:
S2

(array([[  9.98501e-01 +0.00000e+00j,   4.32647e-20 +4.32662e-22j,  -4.99543e-04 -9.99219e-06j,   6.70148e-02 -6.70171e-04j,   4.10466e-18 +0.00000e+00j,  -2.73652e-02 -2.73661e-04j,
          -1.95452e-21 -3.90956e-23j,   1.59559e-05 +4.78819e-07j],
        [  9.98501e-01 +0.00000e+00j,   4.32647e-20 +4.32662e-22j,  -4.99543e-04 -9.99219e-06j,   6.70148e-02 -6.70171e-04j,   4.10466e-18 +0.00000e+00j,  -2.73652e-02 -2.73661e-04j,
          -1.95452e-21 -3.90956e-23j,   1.59559e-05 +4.78819e-07j],
        [  9.98501e-01 +0.00000e+00j,   4.32647e-20 +4.32662e-22j,  -4.99543e-04 -9.99219e-06j,   6.70148e-02 -6.70171e-04j,   4.10466e-18 +0.00000e+00j,  -2.73652e-02 -2.73661e-04j,
          -1.95452e-21 -3.90956e-23j,   1.59559e-05 +4.78819e-07j],
        [  9.98501e-01 +0.00000e+00j,   4.32647e-20 +4.32662e-22j,  -4.99543e-04 -9.99219e-06j,   6.70148e-02 -6.70171e-04j,   4.10466e-18 +0.00000e+00j,  -2.73652e-02 -2.73661e-04j,
          -1.95452e-21 -3.90956e-23j,   1.59559e-05 +4.78819e-07