In [1]:
import numpy as np
import qpms
import spherical_functions as sf, quaternion
qpms.__version__

'0.2.14'

In [2]:
lMax=2
tc = qpms.trans_calculator(lMax)
my, ny = qpms.get_mn_y(lMax)
nelem = len(my)

In [3]:
qpms.yflip_tyty(lMax).reshape((2*nelem,2*nelem))

array([[ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [4]:
d1_cart = np.random.normal(scale=10, size=(3,)) # translation vector in basis 1
rot21_cart = np.random.normal(size=(3,)) # random rotation vector
rot21_quat = quaternion.from_rotation_vector(rot21_cart)
rot21_matrix = quaternion.as_rotation_matrix(rot21_quat) # rotation matrix from basis 1 to basis 2
d2_cart = np.dot(rot21_matrix, d1_cart) # translation vector in basis 2
D21_yy = qpms.WignerD_yy_fromvector(lMax,rot21_cart)
D12_yy = qpms.WignerD_yy_fromvector(lMax,-rot21_cart)

d1_sph = qpms.cart2sph(d1_cart)
r1, th1, fi1 = d1_sph
d2_sph = qpms.cart2sph(d2_cart)
r2, th2, fi2 = d2_sph

S1 = tc.get_AB_arrays(np.array(r1), np.array(th1), np.array(fi1), np.array(True), 3)
S2 = tc.get_AB_arrays(np.array(r2), np.array(th2), np.array(fi2), np.array(True), 3)




In [15]:
( #test for unitarity of the Wigner matrix
    np.all(np.isclose(D12_yy.conj().T,D21_yy)) and  
    np.all(np.isclose(np.dot(D12_yy,D21_yy), np.eye(nelem))) 
)

True

In [21]:
# The "vector" part
S2nA = np.dot(np.dot(D21_yy, S1[0]), D21_yy) # FIXME!!!

In [22]:
S2nA-S2[0]

array([[ 0.04743917-0.00435894j, -0.00470872-0.01398378j,
        -0.01006871+0.01173946j,  0.04603076-0.18432091j,
        -0.00958186+0.00847165j, -0.03004442-0.05760738j,
        -0.09005189-0.01379623j,  0.10420204+0.04070577j],
       [ 0.05692272+0.01973457j,  0.00733591-0.02044294j,
        -0.02551200+0.00699189j,  0.12661886-0.16454722j,
        -0.03115522-0.08103451j, -0.07548977-0.07443503j,
         0.01682261-0.00835097j,  0.15111073+0.13353106j],
       [ 0.01385356+0.01761357j,  0.00888347+0.0022656j ,
        -0.00772059-0.01319341j,  0.04136745-0.05578612j,
         0.11948298-0.05242592j, -0.01879847-0.13187652j,
        -0.06469949+0.15012856j, -0.02193133+0.14110082j],
       [ 0.03176056-0.00938397j, -0.00637480-0.00545451j,
        -0.00151733+0.006046j  ,  0.00386907-0.15259852j,
         0.04316807+0.03386389j, -0.00347348-0.07321214j,
        -0.13573552+0.03663387j,  0.03962384+0.02645222j],
       [ 0.04039226-0.0178003j , -0.01131977-0.0094597j ,
        -0

In [18]:
S2nA

array([[-0.00859653+0.00930361j, -0.00972364+0.01015135j,
         0.00041658-0.00107341j, -0.03143964-0.03018321j,
        -0.03867104-0.05117656j, -0.00783433+0.01128184j,
        -0.04973381-0.04336524j,  0.04439641+0.0179092j ],
       [-0.02607694-0.00461469j, -0.02884136-0.00564j   ,
         0.00235890-0.00047958j,  0.01758760-0.08940138j,
         0.04635160-0.12583514j, -0.02869617-0.00103938j,
         0.02011431-0.13647405j,  0.01863983+0.09833162j],
       [ 0.00702997-0.02160578j,  0.00823072-0.02383229j,
         0.00012622+0.00206139j,  0.07386193+0.02560244j,
         0.10138795+0.05438545j,  0.00430454-0.02425746j,
         0.11355545+0.0333617j , -0.08576881+0.00411305j],
       [ 0.00528984+0.00629714j,  0.00574375+0.00709236j,
        -0.00065733-0.00035602j, -0.02200963+0.01778335j,
        -0.03612204+0.0207255j ,  0.00662627+0.00596787j,
        -0.03199490+0.02848916j,  0.01516291-0.02713158j],
       [ 0.00246817+0.01631093j,  0.00241338+0.0181468j ,
        -0