In [12]:
from qpms.cybspec import BaseSpec
from qpms.cytmatrices import TMatrixGenerator
from qpms.qpms_c import Particle, ScatteringSystem, FinitePointGroup
from qpms.cymaterials import EpsMu, EpsMuGenerator
from qpms.symmetries import point_group_info
import numpy as np

bg = EpsMu(1)
tmgen=TMatrixGenerator.sphere(bg, EpsMu(2.0+0.1j), r=0.5, )

# Create a dummy single-particle scatsystem
bspec = BaseSpec(lMax=2)
particles = [Particle((0,0,0), tmgen, bspec)]
ss, ssw = ScatteringSystem.create(particles, bg, FinitePointGroup(point_group_info['D4h']),1)

In [20]:
ss.saecv_sizes
ss.irrep_names
t, l

(array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int32),
 array([-1,  0,  1, -2, -1,  0,  1,  2, -1,  0,  1, -2, -1,  0,  1,  2], dtype=int32))

In [22]:
t, l, m = bspec.tlm()
tc = [("E" if typ == 2 else "M") for typ in t]
for iri in range(ss.nirreps):
    print(ss.irrep_names[iri])
    sz = ss.saecv_sizes[iri]
    for i in range(sz):
        packed = np.zeros((sz,))
        packed[i] = 1
        unpacked = ss.unpack_vector(packed, iri)
        for j in range(ss.fecv_size):
            if abs(unpacked[j]) > 1e-4:
                print("(%s %d %d)" % (tc[j], l[j], m[j]), unpacked[j])
            

A1'
(E 2 0) (0.8320502943378436+0.554700196225229j)
A1''
(M 2 0) (0.8320502943378436+0.554700196225229j)
A2'
(M 1 0) (0.757391958781565-0.6529605047573891j)
A2''
(E 1 0) (0.757391958781565-0.6529605047573891j)
B1'
(E 2 -2) (-0.7071067811865476+0j)
(E 2 2) (-0.7071067811865475-7.041364024482813e-17j)
B1''
(M 2 -2) (-0.7071067811865476+0j)
(M 2 2) (-0.7071067811865475-7.041364024482813e-17j)
B2'
(E 2 -2) (-0.7071067811865476+0j)
(E 2 2) (0.7071067811865475+7.041364024482813e-17j)
B2''
(M 2 -2) (-0.7071067811865476+0j)
(M 2 2) (0.7071067811865475+7.041364024482813e-17j)
E'
(E 1 -1) (-1+0j)
(M 2 1) (-1+0j)
(E 1 1) (-1+0j)
(M 2 -1) (-1+0j)
E''
(E 2 1) (-1+0j)
(M 1 1) (-1+0j)
(E 2 -1) (1+0j)
(M 1 -1) (-1+0j)
